# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[(b'text', b'Text')], max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('field_type', models.ForeignKey(help_text='create custom risk field types', on_delete=django.db.models.deletion.CASCADE, related_name='risk_field_types', to='app.FieldType', verbose_name='Risk field type')),
            ],
            options={
                'ordering': ['field_type__name'],
            },
        ),
    ]
