# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 12:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=b'{]', help_text='Data for the insurance. Default Null', null=True),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='format',
            field=models.CharField(blank=True, default=b'', help_text='If date-field, specify the format', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='description',
            field=models.CharField(blank=True, help_text='Description for the risk field.', max_length=100, null=True, verbose_name='Description'),
        ),
    ]
