# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Type of the field', max_length=100, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[(b'text', b'Text'), (b'number', b'Number'), (b'date', b'Date'), (b'enum', b'Enum')], help_text='Field type choices', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('extra_fields', models.ManyToManyField(blank=True, to='app.RiskField', verbose_name='Risk fields')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='riskfieldtype',
            name='field_type',
            field=models.ForeignKey(help_text='create custom risk field types', on_delete=django.db.models.deletion.CASCADE, related_name='risk_field_types', to='app.RiskField', verbose_name='Risk field type'),
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
    ]
