# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180209_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('risk_fields', models.ManyToManyField(blank=True, to='app.RiskType', verbose_name='Extra fields')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.RiskType', verbose_name='Payment type')),
            ],
        ),
    ]
