# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180210_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfield',
            name='format',
        ),
    ]
