# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='risk_fields',
        ),
        migrations.AddField(
            model_name='risk',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description of the risk'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='app.RiskType', verbose_name='Risk type'),
        ),
    ]
