# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_riskfield_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='type',
            field=models.CharField(choices=[(b'text', b'Text'), (b'number', b'Number'), (b'date', b'Date'), (b'checkbox', b'Enum')], help_text='Field type choices', max_length=50),
        ),
    ]
