# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180210_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfieldtype',
            name='field_type',
        ),
        migrations.RenameField(
            model_name='risktype',
            old_name='extra_fields',
            new_name='risk_fields',
        ),
        migrations.DeleteModel(
            name='RiskFieldType',
        ),
    ]
