# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180214_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='risk_fields',
            field=models.ManyToManyField(blank=True, null=True, to='app.RiskField', verbose_name='Risk fields'),
        ),
    ]
