# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180215_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='risk_fields',
            field=models.ManyToManyField(blank=True, to='app.RiskField', verbose_name='Risk fields'),
        ),
    ]
