# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180215_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
